source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PGMTimer_Example', :exclusive => true do
  pod "PGMTimer", :path => "../"
end

target 'PGMTimer_Tests', :exclusive => true do
  pod "PGMTimer", :path => "../"

  
end
