language: objective-c

osx_image: xcode7

podfile: Example/Podfile

script:

  xctool
  -workspace Example/PGMTimer.xcworkspace
  -scheme PGMTimer-Example
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
  build 
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO

#before_install:
#  - brew update
#  - brew uninstall xctool && brew install --HEAD xctool