language: objective-c
osx_image: xcode7.2

script:
- set -o pipefail && xcodebuild test -workspace Example/PGMTimer.xcworkspace -scheme PGMTimer-Example -sdk iphoneos9.2 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
